### ISSUE TITLE
issue downloading language server on linux with Zed editor.

### ISSUE THREAD

**Issue by LimaneGaya** [odoo/odoo-ls#457]
**Your setup**
Version: 1.0.3
Operating System: 
Distributor ID: Neon
Description:    KDE neon User Edition
Release:        24.04
Codename:       noble

IDE and/or Integration tool (for example: Vscode - official extension): Zed editor

**Describe the bug**
Starting the language server on zed on linux result in this error:
Language server odoo:

from extension "Odoo" version 1.0.3: Odoo: No asset found for asset name odoo-linux-x64-1.0.3.zip

**To Reproduce**
start zed
install odoo extension
open a project.

**Expected behavior**
the language server to download and run.

**Screenshots**

**Additional context**

**Comment by fda-odoo** [comment]
There was indeed a mistake in the new packaging script. We updated the release on github to use `.tar.gz` extensions for Linux and MacOs, but the change was not included in Zed plugin.
I added Zip files on the release to make the 1.0.3 work, and I'll fix the packaging for Zed for future versions.
Thank you for the report !

**Comment by fda-odoo** [comment]
Fixed in https://github.com/odoo/odoo-zed/pull/2

**Comment by LimaneGaya** [comment]
After the update it still shows:
Language server odoo:

from extension "Odoo" version 1.0.4: Odoo: No asset found for asset name odoo-linux-x64-1.0.4.tar.gz

**Comment by fda-odoo** [comment]
It should work now :) We did a PR again (https://github.com/odoo/odoo-zed/pull/5) and I fixed the download section so the 1.0.4 should be working now. Sorry for the mistake!

**Comment by gaya-lmn** [comment]
Thank you. 
I compiled it and tested it and it does download the correct files.
However i would like to know the features the extension have and the odoo versions it works on.
We currently use odoo 13 and it does not seem to get the model names or fields in the autocomplete.

**Comment by fda-odoo** [comment]
@gaya-lmn  OdooLS doesn't work on versions < 14. I don't remember technically why, but I think there is framework changes we would have to handle and choose not to do.
The code of OdooLS is explicitely rejecting it:
```rust
if _version_major < 14 {
            session.log_message(MessageType::ERROR, String::from("Odoo version is less than 14. The tool only supports version 14 and above. Aborting and switching to non-odoo mode"));
            return false;
        }
```
For version 14.0 and above, you should expect autocompletion, hover, gotodefinition and diagnostics on models, recordset, xml_ids, and classical python stuff.
If you need something specific, do not hesitate to ask :)

**Comment by gaya-lmn** [comment]
Thank you for the quick response, that pretty much sums it all.

**Comment by gaya-lmn** [comment]
I think this issue should be closed.
